// Auto-generated by scripts/build_gallery.py from EXIF metadata.
// Thumbnails: image/gallery/web/<slug>.jpg  Full: image/gallery/full/<slug>.jpg
const GALLERY = [
  {
    "slug": "003120160022250312",
    "src": "003120160022250312.JPEG",
    "date": null,
    "place": null,
    "lat": null,
    "lng": null,
    "w": 324,
    "h": 460
  },
  {
    "slug": "709662860-136845",
    "src": "709662860.136845.jpg",
    "date": "June 2023",
    "place": null,
    "lat": null,
    "lng": null,
    "w": 342,
    "h": 460
  },
  {
    "slug": "711160917-258335",
    "src": "711160917.258335.JPG",
    "date": "July 2023",
    "place": "New York City, USA",
    "lat": 40.70279,
    "lng": -73.98772,
    "w": 345,
    "h": 460
  },
  {
    "slug": "711862776-302778",
    "src": "711862776.302778.JPG",
    "date": "July 2023",
    "place": "Hoboken, USA",
    "lat": 40.75012,
    "lng": -74.02333,
    "w": 460,
    "h": 345
  },
  {
    "slug": "746790422-663053",
    "src": "746790422.663053.JPG",
    "date": "August 2024",
    "place": null,
    "lat": null,
    "lng": null,
    "w": 345,
    "h": 460
  },
  {
    "slug": "746791174-815062",
    "src": "746791174.815062.JPG",
    "date": "August 2024",
    "place": "Weimar, Germany",
    "lat": 50.97956,
    "lng": 11.33423,
    "w": 345,
    "h": 460
  },
  {
    "slug": "785511704-615754",
    "src": "785511704.615754.JPG",
    "date": "November 2025",
    "place": null,
    "lat": null,
    "lng": null,
    "w": 345,
    "h": 460
  },
  {
    "slug": "785920597-367900",
    "src": "785920597.367900.JPG",
    "date": "November 2025",
    "place": null,
    "lat": null,
    "lng": null,
    "w": 307,
    "h": 460
  },
  {
    "slug": "791353257-012872",
    "src": "791353257.012872.jpg",
    "date": "January 2026",
    "place": "Sindong, South Korea",
    "lat": 37.64491,
    "lng": 127.68228,
    "w": 345,
    "h": 460
  },
  {
    "slug": "793606983-495080",
    "src": "793606983.495080.JPG",
    "date": "February 2026",
    "place": "Songgang-dong, South Korea",
    "lat": 36.37355,
    "lng": 127.36194,
    "w": 345,
    "h": 460
  },
  {
    "slug": "805915501-711435",
    "src": "805915501.711435.jpg",
    "date": "July 2026",
    "place": null,
    "lat": null,
    "lng": null,
    "w": 460,
    "h": 345
  },
  {
    "slug": "dscn1025",
    "src": "DSCN1025.JPG",
    "date": "March 2011",
    "place": null,
    "lat": null,
    "lng": null,
    "w": 460,
    "h": 345
  },
  {
    "slug": "day-4-drive-img-7431",
    "src": "Day 4 Drive IMG 7431.JPG",
    "date": "August 2024",
    "place": null,
    "lat": null,
    "lng": null,
    "w": 460,
    "h": 345
  },
  {
    "slug": "fullsizerender",
    "src": "FullSizeRender.HEIC",
    "date": "April 2026",
    "place": "Songgang-dong, South Korea",
    "lat": 36.3761,
    "lng": 127.39438,
    "w": 460,
    "h": 460
  },
  {
    "slug": "img-0230",
    "src": "IMG_0230.HEIC",
    "date": "July 2022",
    "place": "Lauterbrunnen, Switzerland",
    "lat": 46.5476,
    "lng": 7.98092,
    "w": 345,
    "h": 460
  },
  {
    "slug": "img-0785",
    "src": "IMG_0785.JPG",
    "date": null,
    "place": null,
    "lat": null,
    "lng": null,
    "w": 460,
    "h": 460
  },
  {
    "slug": "img-1213",
    "src": "IMG_1213.HEIC",
    "date": "July 2022",
    "place": "Zürich, Switzerland",
    "lat": 47.37303,
    "lng": 8.54137,
    "w": 331,
    "h": 460
  },
  {
    "slug": "img-1512",
    "src": "IMG_1512.JPG",
    "date": "February 2024",
    "place": "Seoul, South Korea",
    "lat": 37.56774,
    "lng": 126.93974,
    "w": 460,
    "h": 460
  },
  {
    "slug": "img-1647",
    "src": "IMG_1647.JPG",
    "date": null,
    "place": null,
    "lat": null,
    "lng": null,
    "w": 345,
    "h": 460
  },
  {
    "slug": "img-2214-2",
    "src": "IMG_2214 2.JPG",
    "date": "May 2026",
    "place": "Songgang-dong, South Korea",
    "lat": 36.36879,
    "lng": 127.36294,
    "w": 345,
    "h": 460
  },
  {
    "slug": "img-2520",
    "src": "IMG_2520.JPG",
    "date": "May 2023",
    "place": null,
    "lat": null,
    "lng": null,
    "w": 345,
    "h": 460
  },
  {
    "slug": "img-2601",
    "src": "IMG_2601.heic",
    "date": "June 2026",
    "place": "Songgang-dong, South Korea",
    "lat": 36.37611,
    "lng": 127.39434,
    "w": 460,
    "h": 460
  },
  {
    "slug": "img-2634",
    "src": "IMG_2634.HEIC",
    "date": "April 2025",
    "place": "Yokohama, Japan",
    "lat": 35.45315,
    "lng": 139.63745,
    "w": 460,
    "h": 345
  },
  {
    "slug": "img-2743",
    "src": "IMG_2743.JPG",
    "date": "May 2023",
    "place": "Seoul, South Korea",
    "lat": 37.57459,
    "lng": 126.97426,
    "w": 345,
    "h": 460
  },
  {
    "slug": "img-2790",
    "src": "IMG_2790.JPG",
    "date": "June 2026",
    "place": "Stockholm, Sweden",
    "lat": 59.33649,
    "lng": 18.07667,
    "w": 345,
    "h": 460
  },
  {
    "slug": "img-3033",
    "src": "IMG_3033.HEIC",
    "date": "June 2023",
    "place": "Jangheung, South Korea",
    "lat": 37.65855,
    "lng": 126.97807,
    "w": 460,
    "h": 345
  },
  {
    "slug": "img-3162",
    "src": "IMG_3162.HEIC",
    "date": "May 2025",
    "place": "Tokyo, Japan",
    "lat": 35.65559,
    "lng": 139.74966,
    "w": 345,
    "h": 460
  },
  {
    "slug": "img-3444",
    "src": "IMG_3444.HEIC",
    "date": "July 2026",
    "place": "Chelsea, UK",
    "lat": 51.50179,
    "lng": -0.16061,
    "w": 345,
    "h": 460
  },
  {
    "slug": "img-3447",
    "src": "IMG_3447.JPG",
    "date": "July 2026",
    "place": "Clerkenwell, UK",
    "lat": 51.51866,
    "lng": -0.11941,
    "w": 345,
    "h": 460
  },
  {
    "slug": "img-3549",
    "src": "IMG_3549.HEIC",
    "date": "July 2020",
    "place": "Stanley, UK",
    "lat": 54.88611,
    "lng": -1.65621,
    "w": 460,
    "h": 345
  },
  {
    "slug": "img-3733",
    "src": "IMG_3733.HEIC",
    "date": "July 2024",
    "place": "Tokyo, Japan",
    "lat": 35.65977,
    "lng": 139.73215,
    "w": 345,
    "h": 460
  },
  {
    "slug": "img-3935",
    "src": "IMG_3935.HEIC",
    "date": "July 2024",
    "place": "Tokyo, Japan",
    "lat": 35.69366,
    "lng": 139.76807,
    "w": 345,
    "h": 460
  },
  {
    "slug": "img-4054",
    "src": "IMG_4054.JPG",
    "date": "September 2018",
    "place": "Gyeongsan-si, South Korea",
    "lat": 35.86724,
    "lng": 128.71182,
    "w": 460,
    "h": 307
  },
  {
    "slug": "img-4463",
    "src": "IMG_4463.heic",
    "date": "July 2023",
    "place": "Long Island City, USA",
    "lat": 40.74944,
    "lng": -73.97134,
    "w": 345,
    "h": 460
  },
  {
    "slug": "img-4632",
    "src": "IMG_4632.heic",
    "date": "November 2021",
    "place": "Seoul, South Korea",
    "lat": 37.57487,
    "lng": 126.96711,
    "w": 259,
    "h": 460
  },
  {
    "slug": "img-4683",
    "src": "IMG_4683.JPG",
    "date": "July 2023",
    "place": "Long Island City, USA",
    "lat": 40.76532,
    "lng": -73.93156,
    "w": 345,
    "h": 460
  },
  {
    "slug": "img-4729",
    "src": "IMG_4729.JPG",
    "date": null,
    "place": null,
    "lat": null,
    "lng": null,
    "w": 460,
    "h": 345
  },
  {
    "slug": "img-5131",
    "src": "IMG_5131.JPG",
    "date": "November 2021",
    "place": "Goyang-si, South Korea",
    "lat": 37.66736,
    "lng": 126.74486,
    "w": 460,
    "h": 345
  },
  {
    "slug": "img-6373",
    "src": "IMG_6373.HEIC",
    "date": "July 2023",
    "place": "Hoboken, USA",
    "lat": 40.73636,
    "lng": -74.02533,
    "w": 460,
    "h": 345
  },
  {
    "slug": "img-6660",
    "src": "IMG_6660.HEIC",
    "date": "October 2024",
    "place": "Bloomfield, USA",
    "lat": 40.44489,
    "lng": -79.94869,
    "w": 345,
    "h": 460
  },
  {
    "slug": "img-7139",
    "src": "IMG_7139.JPG",
    "date": null,
    "place": null,
    "lat": null,
    "lng": null,
    "w": 329,
    "h": 460
  },
  {
    "slug": "img-7543",
    "src": "IMG_7543.HEIC",
    "date": "November 2019",
    "place": "Paris, France",
    "lat": 48.85999,
    "lng": 2.32712,
    "w": 460,
    "h": 460
  },
  {
    "slug": "img-7560",
    "src": "IMG_7560.HEIC",
    "date": "November 2019",
    "place": "Paris, France",
    "lat": 48.86004,
    "lng": 2.32629,
    "w": 345,
    "h": 460
  },
  {
    "slug": "img-7677",
    "src": "IMG_7677.HEIC",
    "date": "October 2025",
    "place": "Gyeongsan-si, South Korea",
    "lat": 35.86717,
    "lng": 128.71223,
    "w": 460,
    "h": 305
  },
  {
    "slug": "img-7706",
    "src": "IMG_7706.HEIC",
    "date": "October 2025",
    "place": "Daegu, South Korea",
    "lat": 35.81528,
    "lng": 128.64394,
    "w": 460,
    "h": 460
  },
  {
    "slug": "img-7890",
    "src": "IMG_7890.HEIC",
    "date": "October 2025",
    "place": "Stockholm, Sweden",
    "lat": 59.3386,
    "lng": 18.03376,
    "w": 460,
    "h": 460
  },
  {
    "slug": "img-8360",
    "src": "IMG_8360.HEIC",
    "date": "December 2024",
    "place": "Seoul, South Korea",
    "lat": 37.55512,
    "lng": 126.92971,
    "w": 345,
    "h": 460
  },
  {
    "slug": "img-8364",
    "src": "IMG_8364.HEIC",
    "date": "November 2025",
    "place": "Helsinki, Finland",
    "lat": 60.16964,
    "lng": 24.95278,
    "w": 460,
    "h": 345
  },
  {
    "slug": "img-8403",
    "src": "IMG_8403.HEIC",
    "date": "November 2025",
    "place": "Helsinki, Finland",
    "lat": 60.16808,
    "lng": 24.94367,
    "w": 345,
    "h": 460
  },
  {
    "slug": "img-8806",
    "src": "IMG_8806.HEIC",
    "date": "November 2025",
    "place": "Copenhagen, Denmark",
    "lat": 55.67228,
    "lng": 12.57727,
    "w": 345,
    "h": 460
  },
  {
    "slug": "img-8888",
    "src": "IMG_8888.HEIC",
    "date": "June 2022",
    "place": "Paris, France",
    "lat": 48.85984,
    "lng": 2.32678,
    "w": 345,
    "h": 460
  },
  {
    "slug": "img-8928",
    "src": "IMG_8928.HEIC",
    "date": "November 2023",
    "place": "Seoul, South Korea",
    "lat": 37.53346,
    "lng": 126.97234,
    "w": 345,
    "h": 460
  },
  {
    "slug": "img-9048",
    "src": "IMG_9048.HEIC",
    "date": "November 2025",
    "place": "Stockholm, Sweden",
    "lat": 59.32083,
    "lng": 18.06235,
    "w": 345,
    "h": 460
  },
  {
    "slug": "img-9269",
    "src": "IMG_9269.JPG",
    "date": "February 2025",
    "place": null,
    "lat": null,
    "lng": null,
    "w": 345,
    "h": 460
  },
  {
    "slug": "img-9646",
    "src": "IMG_9646.HEIC",
    "date": "July 2022",
    "place": "Interlaken, Switzerland",
    "lat": 46.68476,
    "lng": 7.86048,
    "w": 345,
    "h": 460
  },
  {
    "slug": "img-9655",
    "src": "IMG_9655.heic",
    "date": "June 2022",
    "place": "Neuilly-sur-Seine, France",
    "lat": 48.85995,
    "lng": 2.29155,
    "w": 345,
    "h": 460
  },
  {
    "slug": "soda1759329803",
    "src": "SODA1759329803.JPG",
    "date": null,
    "place": null,
    "lat": null,
    "lng": null,
    "w": 460,
    "h": 259
  }
];
