#!/usr/bin/env python3
"""
Rebuild the photo-sphere gallery.

Drop new photos (JPG / HEIC) into image/gallery/, then run this script to:
  1. read each photo's EXIF date + GPS,
  2. reverse-geocode GPS to a "City, Country" place name (offline),
  3. write web-optimized copies to image/gallery/web (thumbs) and
     image/gallery/full (lightbox size),
  4. regenerate js/gallery-data.js (the GALLERY array the page reads).

One-time setup:
    python3 -m venv .venv
    .venv/bin/pip install Pillow pillow-heif reverse_geocoder

Run:
    .venv/bin/python scripts/build_gallery.py
"""
import os, re, json
from PIL import Image, ImageOps, ExifTags
import pillow_heif
import reverse_geocoder as rg
pillow_heif.register_heif_opener()

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "image/gallery")
THUMB_DIR = os.path.join(SRC, "web")
FULL_DIR = os.path.join(SRC, "full")
DATA = os.path.join(ROOT, "js/gallery-data.js")
os.makedirs(THUMB_DIR, exist_ok=True)
os.makedirs(FULL_DIR, exist_ok=True)

GPS_IFD = ExifTags.IFD.GPSInfo
MONTHS = ["", "January", "February", "March", "April", "May", "June", "July",
          "August", "September", "October", "November", "December"]
# country-code -> friendly name (extend as you travel to new places)
CC = {"US": "USA", "KR": "South Korea", "JP": "Japan", "CN": "China", "GB": "UK",
      "FR": "France", "IT": "Italy", "DE": "Germany", "ES": "Spain", "CH": "Switzerland",
      "CA": "Canada", "AU": "Australia", "NL": "Netherlands", "SG": "Singapore",
      "TH": "Thailand", "VN": "Vietnam", "HK": "Hong Kong", "TW": "Taiwan", "AT": "Austria",
      "CZ": "Czechia", "BE": "Belgium", "PT": "Portugal", "GR": "Greece", "MX": "Mexico",
      "AD": "Andorra", "AE": "UAE", "SE": "Sweden", "FI": "Finland", "DK": "Denmark",
      "NO": "Norway", "IE": "Ireland", "IS": "Iceland", "PL": "Poland", "HU": "Hungary"}


def to_deg(val, ref):
    d, m, s = [float(x) for x in val]
    dec = d + m / 60 + s / 3600
    return -dec if ref in ("S", "W") else dec


def slugify(f):
    return re.sub(r"[^a-zA-Z0-9]+", "-", os.path.splitext(f)[0]).strip("-").lower()


def clean_city(name):
    name = re.split(r"[/(]", name)[0].strip()
    return name.replace("Zuerich", "Zürich").replace("OEstermalm", "Stockholm")


def main():
    files = sorted(f for f in os.listdir(SRC)
                   if not f.startswith(".") and os.path.isfile(os.path.join(SRC, f)))
    items, geo = [], []
    for f in files:
        path = os.path.join(SRC, f)
        slug = slugify(f)
        it = {"slug": slug, "src": f, "date": None, "place": None,
              "lat": None, "lng": None, "w": None, "h": None}
        try:
            img = Image.open(path)
            exif = img.getexif()
            raw = None
            try:
                ex = exif.get_ifd(ExifTags.IFD.Exif)
                raw = ex.get(36867) or ex.get(36868)
            except Exception:
                pass
            raw = raw or exif.get(36867) or exif.get(306)
            if raw:
                m = re.match(r"(\d{4}):(\d{2}):", str(raw))
                if m and 1 <= int(m.group(2)) <= 12:
                    it["date"] = f"{MONTHS[int(m.group(2))]} {int(m.group(1))}"
            try:
                gps = exif.get_ifd(GPS_IFD)
                if gps and gps.get(2) and gps.get(4):
                    it["lat"] = round(to_deg(gps.get(2), gps.get(1)), 5)
                    it["lng"] = round(to_deg(gps.get(4), gps.get(3)), 5)
                    geo.append((len(items), it["lat"], it["lng"]))
            except Exception:
                pass

            img = ImageOps.exif_transpose(img).convert("RGB")
            full = img.copy(); full.thumbnail((1600, 1600), Image.LANCZOS)
            full.save(os.path.join(FULL_DIR, slug + ".jpg"), "JPEG", quality=82, optimize=True)
            thumb = img.copy(); thumb.thumbnail((460, 460), Image.LANCZOS)
            it["w"], it["h"] = thumb.size
            thumb.save(os.path.join(THUMB_DIR, slug + ".jpg"), "JPEG", quality=72, optimize=True)
            print("ok  ", f)
        except Exception as e:
            print("skip", f, "-", e)
            continue
        items.append(it)

    if geo:
        res = rg.search([(la, ln) for _, la, ln in geo], mode=1)  # mode=1 avoids multiprocessing
        for (idx, _, _), r in zip(geo, res):
            city = clean_city((r.get("name") or r.get("admin1") or "").strip())
            country = CC.get((r.get("cc") or "").strip(), (r.get("cc") or "").strip())
            items[idx]["place"] = ", ".join(p for p in (city, country) if p)

    with open(DATA, "w") as fh:
        fh.write("// Auto-generated by scripts/build_gallery.py from EXIF metadata.\n")
        fh.write("// Thumbnails: image/gallery/web/<slug>.jpg  Full: image/gallery/full/<slug>.jpg\n")
        fh.write("const GALLERY = " + json.dumps(items, ensure_ascii=False, indent=2) + ";\n")

    print(f"\n{len(items)} photos | {sum(1 for i in items if i['date'])} dated | "
          f"{sum(1 for i in items if i['place'])} placed  ->  {os.path.relpath(DATA, ROOT)}")


if __name__ == "__main__":
    main()
